COINEX_API_KEY = 'B49826D1B36B4A1ABF02DF0A30AF2FD3'
COINEX_API_SECRET = '754B822312C702ABCA0A4A0DBA224143DF23173362DDF338'
time_interval = '1d'

BINANCE_API_KEY = 'SvvG1ooYWYpLEZnSMoMbO2qN246CfnCFvB87sVOISg6KPkukq07BpmkqWfWC62yT'
BINANCE_API_SECRET = 'RhAuSUL6iipT1o1yA9yDTdZoRTdqcLM2KSPYxtvrLMBmGlY8KeljnaNoPfFfhltf'


API_KEY = 'swNCkZLoqzFnYPreUDrFAAnoAxsx16PcJSDlU3AEpep7MwaOCVXzq3YHUDJkZvu8'
API_SECRET = 'f7774SEvatAbZJHNP6NYZu6dtAb6zxYUBmxQp6c8d90PbNvlvKLYl1ofF7A1J4qn'

#TELEGRAM_TOKEN = '7619077339:AAGvLzsABJRFKsv50TgI1XxMNhVvtED-E_4'
TELEGRAM_TOKEN = '7291265041:AAHAsg1hnD1fe4eINhfd-86425ReI04lYJY'
CHAT_ID = '1385370555'

TELEGRAM_TOKEN_EXITE = '7291265041:AAHAsg1hnD1fe4eINhfd-86425ReI04lYJY'
TELEGRAM_CHAT_ID = '1385370555'
TELEGRAM_TOKEN_EXIT = '7619077339:AAGvLzsABJRFKsv50TgI1XxMNhVvtED-E_4'

# 3Commas webhook details
THREE_COMMAS_WEBHOOK_URL = "https://api.3commas.io/signal_bots/webhooks"

#SECRET_1 = "eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTEyOTA5fQ.gjDjD0PDj_RdOq-L3HTLiy-i22gBhO9xN6mIbSlTwBg"
#SECRET_2 = "eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTEyOTA5fQ.gjDjD0PDj_RdOq-L3HTLiy-i22gBhO9xN6mIbSlTwBg"

SECRET_1 = "eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo"
SECRET_2 = "eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6ODI4MzV9.ccZIwRRxe781qP0Mtlx62NIkmKyUGs155h433uxE-M0"
# Telegram Bot Token
#TELEGRAM_TOKEN = "7619077339:AAGvLzsABJRFKsv50TgI1XxMNhVvtED-E_4"

# Trading Bot UUID
#BOT_UUID_2 = "4b96d40e-7c80-497a-a2e4-ad9013f82435"
#BOT_UUID_1 = "1cd58dbb-1d9f-4607-a411-758d90ded041"
# Trading Bot UUID
BOT_UUID_1 = "8fb612f0-4859-43e5-bb7d-99a93785cfc2"
BOT_UUID_2 = "94de674e-e3f6-4c9f-9cc2-4a70e9acf79d"

# List of futures trading pairs (symbols)
symbols = [
    'WLDUSDT', 'SEIUSDT', 'CYBERUSDT', 'ARKUSDT','NTRNUSDT', 'TIAUSDT', 'MEMEUSDT',
    'ORDIUSDT', 'BEAMXUSDT', 'BLURUSDT', 'JTOUSDT', '1000SATSUSDT',
    '1000BONKUSDT', 'ACEUSDT', 'NFPUSDT', 'AIUSDT', 'XAIUSDT', 'MANTAUSDT', 'POWRUSDT',
    'JASMYUSDT', 'RNDRUSDT',
    'BICOUSDT', 'FXSUSDT', 'HIGHUSDT', 'CVXUSDT', 'PEOPLEUSDT', 'SPELLUSDT',
    'JOEUSDT', 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'API3USDT',
    'WOOUSDT', 'ASTRUSDT', 'GMTUSDT', 'APEUSDT',
    'STEEMUSDT', 'GALUSDT', 'LDOUSDT', 'BTCUSDT', 'ETHUSDT',
    'BNBUSDT', 'NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'EOSUSDT', 'IOTAUSDT', 'XLMUSDT',
    'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT', 'VETUSDT',
    'LINKUSDT', 'WAVESUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT',
    'XMRUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT', 'DASHUSDT', 'OMGUSDT', 'THETAUSDT', 'ENJUSDT',
    'MATICUSDT', 'ATOMUSDT', 'ONEUSDT', 'FTMUSDT', 'ALGOUSDT', 'DOGEUSDT',
    'DUSKUSDT', 'ANKRUSDT', 'MTLUSDT', 'DENTUSDT',
    'KEYUSDT', 'STMXUSDT', 'CHZUSDT', 'BANDUSDT',
    'XTZUSDT', 'RENUSDT', 'RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT',
    'RLCUSDT', 'BCHUSDT', 'OGNUSDT',
    'LSKUSDT', 'BNTUSDT', 'MBLUSDT',
    'COTIUSDT', 'STPTUSDT', 'SOLUSDT', 'CTSIUSDT', 'CHRUSDT',
    'MDTUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT',
    'ZENUSDT', 'SNXUSDT', 'DGBUSDT', 'SXPUSDT', 'MKRUSDT',
    'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BALUSDT', 'BLZUSDT',
    'ANTUSDT', 'CRVUSDT', 'SANDUSDT', 'OCEANUSDT', 'NMRUSDT', 'DOTUSDT', 'LUNA2USDT', 'RSRUSDT',
    'TRBUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'RUNEUSDT', 'UMAUSDT',
    'BELUSDT', 'UNIUSDT', 'OXTUSDT', 'AVAXUSDT', 'FLMUSDT',
    'XVSUSDT', 'ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'INJUSDT', 'AUDIOUSDT', 'CTKUSDT',
    'AXSUSDT', 'STRAXUSDT', 'UNFIUSDT', 'ROSEUSDT', 'XEMUSDT', 'SKLUSDT',
    'GRTUSDT', '1INCHUSDT', 'REEFUSDT', 'CELOUSDT', 'RIFUSDT',
    'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'LITUSDT', 'SFPUSDT', 'DODOXUSDT', 'CAKEUSDT',
    'BADGERUSDT', 'ALICEUSDT', 'LINAUSDT', 'PERPUSDT', 'SUPERUSDT',
    'CFXUSDT', 'TLMUSDT',
    'BAKEUSDT', 'SLPUSDT', '1000SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT',
    'XVGUSDT', 'ATAUSDT', 'APTUSDT', 'ARBUSDT'
]

# Time interval for fetching historical data
time_interval = '1d'  # You can change this to '4h', '1d', etc.
