# config.yaml
# NEVER commit this file to version control or share it
# This is for REAL Binance mainnet (live trading)

binance:
  api_key:     "8Vk0OOD3G2YqlcUcsl00t8f7Sl87MyTDzOs3cKNlyQzeoiDhLuTFLhidst9QoOb2"
  api_secret:  "RKy9Ooji40608olqCa7VWwkTbtQyoEzpqL2keyuAmAmTnobURma3eFvxX1olGvjz"


trading:
  use_testnet: false          # ← change to false for real trading!
  max_allowed_loss_usdt: -10.0


telegram:
  token: "8524530031:AAEThbIoDk1snrWE4gAfIHUX6HU8bpIcI24"
  chat_id: "-5291509752"           # group ID (negative)
  alert_bot_user_id: "7904776370"      # ← ID of your alert bot

