# config.yaml
# NEVER commit this file to version control or share it
# This is for REAL Binance mainnet (live trading)

binance:
  api_key:     "8Vk0OOD3G2YqlcUcsl00t8f7Sl87MyTDzOs3cKNlyQzeoiDhLuTFLhidst9QoOb2"
  api_secret:  "RKy9Ooji40608olqCa7VWwkTbtQyoEzpqL2keyuAmAmTnobURma3eFvxX1olGvjz"


telegram:
  token: 7904776370:AAFB77L9ninv5r0wP_g4vTTkzLYO6-7bdY0
  chat_id: "1385370555"  


trading:
  use_testnet: false          # ← change to false for real trading!
  max_allowed_loss_usdt: -10.0
